### ISSUE TITLE
we can run multiple pairs at the same time

### ISSUE THREAD

**Issue by duchuAz** [zyairelai/futures-omax#9]
how to run it...?
thx u

**Comment by zyairelai** [comment]
I do not recommend you to run multiple coins at the same time when you just started. 

Perhaps you might need to check and confirm the entry and exit of futures-omax before going big and running multiple coins, considering your wallet management from `README.MD`

However if you insist to run multiple coins, you can open different terminals and `python3 run.py` and choose your coins, currently there are 3 pairs, just type in the number and hit enter.

**Comment by duchuAz** [comment]
"However if you insist to run multiple coins, you can open different terminals and python3 run.py and choose your coins, currently there are 3 pairs, just type in the number and hit enter."

I tried it but it doesn't work, after choosing a different currency, it doesn't work
thx u about advice

**Comment by zyairelai** [comment]
Can you show me your `config.py` and your terminal screenshots on how did you run it?

The main recommendation is BTC, ETH and BNB, all the default and minimum requirements are listed commented in `config.py`

What do you mean it doesn't work? What error are you facing?

**Comment by duchuAz** [comment]
thank you, really sorry i typed the wrong command, it still works
